FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
&& pip install --no-cache-dir plotly pillow \
&& pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch torchvision

COPY ui ./ui
COPY ml ./ml

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
