version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: gold-api
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    volumes:
      - ../api:/app/api:ro
      - ../ml:/app/ml:ro
      - hf_cache:/root/.cache/huggingface:rw
    restart: always

  ui:
    build:
      context: ..
      dockerfile: infra/Dockerfile.ui
    container_name: gold-ui
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_FILEWATCHER_TYPE=none
    volumes:
      - ../ui:/app/ui:ro
      - ../ml:/app/ml:ro
      - hf_cache:/root/.cache/huggingface:rw
    restart: always

  nginx:
    image: nginx:alpine
    container_name: gold-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - ui
    restart: always

volumes:
  hf_cache: