FROM python:3.11-slim

WORKDIR /app

COPY requirements-ui.txt .
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential \
 && pip install --no-cache-dir -r requirements-ui.txt \
 && apt-get remove -y gcc build-essential \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*

COPY ui ./ui
COPY ml ./ml

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
