events {}

http {
    server {
        listen 80;

        # API FastAPI
        location /api/ {
            proxy_pass http://api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # UI Streamlit
        location /app/ {
            proxy_pass http://ui:8501/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Default route
        location / {
            return 302 /app/;
        }
    }
}
